// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoDepreciación.Infrastructure.Data;

#nullable disable

namespace ProyectoDepreciación.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260923142724_Activos_Separado")]
    partial class Activos_Separado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoDepreciación.Domain.Entities.Activo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CostoAdquisicion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAdquisicion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PorcentajeAnual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorResidual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VidaUtilAnios")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Activos");
                });
#pragma warning restore 612, 618
        }
    }
}
